-- =============================================================================
-- SHADOW FORGE — GENESIS SET CARD SEED (auto-generated from src/game/cards.ts)
-- 150 collectible cards. Idempotent via ON CONFLICT (code).
-- =============================================================================

insert into cards (code, name, clan, card_type, rarity, cost, attack, health, rules_text, image_url) values
  ('str_recruit', 'Foot Ninja', 'Oni', 'unit', 'common', 1, 2, 1, null, '🗡️'),
  ('str_initiate', 'Dojo Initiate', 'Oni', 'unit', 'common', 1, 1, 2, null, '🥋'),
  ('str_warhound', 'War Hound', 'Oni', 'unit', 'common', 2, 2, 1, 'Haste', '🐕'),
  ('str_berserker', 'Blade Fury', 'Oni', 'unit', 'common', 2, 3, 2, null, '🪓'),
  ('str_brawler', 'Pit Brawler', 'Oni', 'unit', 'rare', 2, 2, 2, 'Momentum', '🥊'),
  ('str_wolf', 'Shadow Hound', 'Oni', 'unit', 'common', 3, 3, 2, 'Wither', '🐺'),
  ('str_ronin', 'Wandering Ronin', 'Oni', 'unit', 'common', 3, 4, 2, null, '🧖'),
  ('str_oniblade', 'Oni Blademaster', 'Oni', 'unit', 'rare', 3, 3, 3, 'Momentum', '⚔️'),
  ('str_breaker', 'Gate Breaker', 'Oni', 'unit', 'rare', 4, 4, 3, 'Pierce', '🔨'),
  ('str_warlord', 'Clan Warlord', 'Oni', 'unit', 'rare', 4, 4, 4, 'Battlecry: give your other units +1/+0.', '🎌'),
  ('str_sentinel', 'Stone Sentinel', 'Oni', 'unit', 'common', 4, 2, 6, 'Guard', '🗿'),
  ('str_marauder', 'Mountain Marauder', 'Oni', 'unit', 'rare', 5, 5, 4, 'Wither', '⛏️'),
  ('str_ogre', 'Oni Brute', 'Oni', 'unit', 'common', 5, 6, 5, null, '👹'),
  ('str_executioner', 'Oni Executioner', 'Oni', 'unit', 'epic', 5, 4, 4, 'Battlecry: deal 3 damage to an enemy unit.', '🪦'),
  ('str_champion', 'Samurai Champion', 'Oni', 'unit', 'rare', 6, 5, 5, 'Guard', '🛡️'),
  ('str_juggernaut', 'Iron Juggernaut', 'Oni', 'unit', 'common', 6, 6, 6, null, '🐲'),
  ('str_avatar', 'Avatar of War', 'Oni', 'unit', 'legendary', 6, 5, 5, 'Flurry', '🔱'),
  ('str_titan', 'Stone Oni', 'Oni', 'unit', 'legendary', 7, 8, 8, 'Pierce', '🏔️'),
  ('str_warbringer', 'Warbringer', 'Oni', 'unit', 'rare', 7, 7, 6, 'Momentum. Battlecry: give your other units +1/+1.', '🎺'),
  ('str_demon', 'Demon General', 'Oni', 'unit', 'epic', 8, 8, 8, 'Battlecry: give your other units +2/+2.', '😈'),
  ('str_rage', 'Blood Fury', 'Oni', 'spell', 'common', 1, null, null, 'Give a friendly unit +2/+1 and Haste.', '🔥'),
  ('str_berserk', 'Reckless Charge', 'Oni', 'spell', 'common', 1, null, null, 'Give a friendly unit +2/+2.', '💢'),
  ('str_smash', 'Iron Crush', 'Oni', 'spell', 'common', 2, null, null, 'Deal 4 damage to a unit.', '💥'),
  ('str_bloodrage', 'Bloodrage', 'Oni', 'spell', 'rare', 2, null, null, 'Give a friendly unit +3/+0 and Momentum.', '🩸'),
  ('str_challenge', 'War Banner', 'Oni', 'spell', 'common', 2, null, null, 'Give a friendly unit +1/+2.', '🚩'),
  ('str_warcry', 'War Drums', 'Oni', 'spell', 'rare', 3, null, null, 'Give your units +1/+1.', '🥁'),
  ('str_cleave', 'Cleaving Strike', 'Oni', 'spell', 'epic', 3, null, null, 'Deal 5 damage to a unit.', '🌋'),
  ('str_warpath', 'Warpath', 'Oni', 'spell', 'rare', 4, null, null, 'Give your units +2/+0 and Haste.', '🐾'),
  ('str_onislam', 'Oni Slam', 'Oni', 'spell', 'epic', 4, null, null, 'Deal 6 damage to a unit.', '☄️'),
  ('str_summon_oni', 'Summon Oni', 'Oni', 'spell', 'rare', 5, null, null, 'Summon two 3/3 Oni Spirits.', '🔺'),
  ('wis_scholar', 'Scroll Apprentice', 'Sage', 'unit', 'common', 1, 1, 2, 'Battlecry: draw a card.', '📜'),
  ('wis_acolyte', 'Ink Acolyte', 'Sage', 'unit', 'common', 1, 2, 1, null, '🖌️'),
  ('wis_sage', 'Owl Sensei', 'Sage', 'unit', 'common', 2, 2, 2, null, '🦉'),
  ('wis_diviner', 'Star Diviner', 'Sage', 'unit', 'rare', 2, 1, 3, 'Battlecry: draw a card.', '🌟'),
  ('wis_mystic', 'Storm Mystic', 'Sage', 'unit', 'common', 3, 3, 2, 'Battlecry: deal 1 damage to any target.', '🌩️'),
  ('wis_oracle', 'Fortune Seer', 'Sage', 'unit', 'common', 3, 2, 3, 'Battlecry: draw a card.', '🔮'),
  ('wis_mirror', 'Mirror Image', 'Sage', 'unit', 'common', 4, 3, 4, 'Spellshield', '🪞'),
  ('wis_warden', 'Rune Warden', 'Sage', 'unit', 'common', 4, 2, 5, 'Guard', '🪧'),
  ('wis_seer2', 'Tea House Seer', 'Sage', 'unit', 'rare', 4, 3, 3, 'Battlecry: draw a card.', '🍵'),
  ('wis_familiar', 'Paper Crane', 'Sage', 'unit', 'common', 2, 1, 1, 'Flight. Battlecry: draw a card.', '🕊️'),
  ('wis_stormcaller', 'Storm Caller', 'Sage', 'unit', 'rare', 5, 3, 5, 'Battlecry: deal 2 damage to all enemy units.', '⛈️'),
  ('wis_archmage', 'Genjutsu Master', 'Sage', 'unit', 'rare', 5, 4, 4, 'Battlecry: draw 2 cards.', '🧙'),
  ('wis_timebender', 'Time Weaver', 'Sage', 'unit', 'rare', 6, 4, 5, 'Battlecry: draw 2 cards.', '⏳'),
  ('wis_elder', 'Elder Sage', 'Sage', 'unit', 'epic', 6, 5, 5, 'Spellshield. Battlecry: deal 3 damage to any target.', '🧓'),
  ('wis_kitsune', 'Nine-Tail Kitsune', 'Sage', 'unit', 'legendary', 7, 6, 6, 'Battlecry: deal 3 damage to all enemy units.', '🦊'),
  ('wis_celestial', 'Celestial Dragon', 'Sage', 'unit', 'legendary', 8, 7, 7, 'Battlecry: deal 4 damage to any target and draw a card.', '🐉'),
  ('wis_bolt', 'Lightning Seal', 'Sage', 'spell', 'common', 1, null, null, 'Deal 2 damage to any target.', '⚡'),
  ('wis_spark', 'Spirit Spark', 'Sage', 'spell', 'common', 1, null, null, 'Deal 1 damage to any target. Draw a card.', '✨'),
  ('wis_insight', 'Forbidden Scroll', 'Sage', 'spell', 'common', 2, null, null, 'Draw 2 cards.', '📖'),
  ('wis_frost', 'Binding Talisman', 'Sage', 'spell', 'common', 2, null, null, 'Deal 3 damage to an enemy unit.', '🧿'),
  ('wis_zap', 'Static Jolt', 'Sage', 'spell', 'common', 2, null, null, 'Deal 3 damage to any target.', '🔌'),
  ('wis_recall', 'Recall Scroll', 'Sage', 'spell', 'common', 2, null, null, 'Deal 1 damage to any target. Draw 2 cards.', '📃'),
  ('wis_chain', 'Chain Lightning', 'Sage', 'spell', 'rare', 3, null, null, 'Deal 2 damage to all enemy units.', '🌐'),
  ('wis_scry', 'Far Sight', 'Sage', 'spell', 'rare', 3, null, null, 'Draw 3 cards.', '👁️'),
  ('wis_blast', 'Mind Snare', 'Sage', 'spell', 'common', 4, null, null, 'Deal 3 damage to any target. Draw a card.', '🌀'),
  ('wis_squall', 'Howling Squall', 'Sage', 'spell', 'common', 4, null, null, 'Deal 1 damage to all units. Draw a card.', '🍃'),
  ('wis_purge', 'Spirit Purge', 'Sage', 'spell', 'epic', 4, null, null, 'Destroy an enemy unit.', '🕯️'),
  ('wis_meteor', 'Fire Storm Jutsu', 'Sage', 'spell', 'epic', 5, null, null, 'Deal 3 damage to all enemy units.', '☄️'),
  ('wis_judgment', 'Heaven''s Judgment', 'Sage', 'spell', 'rare', 5, null, null, 'Deal 5 damage to any target.', '🌠'),
  ('wis_nova', 'Arcane Nova', 'Sage', 'spell', 'epic', 6, null, null, 'Deal 4 damage to all enemy units.', '💫'),
  ('agi_scout', 'Shadow Scout', 'Shadow', 'unit', 'common', 1, 1, 1, 'Haste', '🏃'),
  ('agi_genin', 'Genin Trainee', 'Shadow', 'unit', 'common', 1, 1, 2, 'Stealth', '🌑'),
  ('agi_rogue', 'Smoke Ninja', 'Shadow', 'unit', 'common', 2, 2, 1, 'Stealth', '💨'),
  ('agi_duelist', 'Twin-Blade Ninja', 'Shadow', 'unit', 'common', 2, 2, 2, 'Haste', '⚔️'),
  ('agi_kunoichi', 'Kunoichi Initiate', 'Shadow', 'unit', 'rare', 2, 2, 2, 'Ambush', '🌸'),
  ('agi_falcon', 'Hawk Rider', 'Shadow', 'unit', 'common', 3, 2, 3, 'Flight', '🦅'),
  ('agi_assassin', 'Silent Assassin', 'Shadow', 'unit', 'rare', 3, 3, 2, 'Stealth', '🥷'),
  ('agi_venomdart', 'Venom Dancer', 'Shadow', 'unit', 'rare', 3, 2, 2, 'Venom', '🐍'),
  ('agi_shadowstep', 'Shadowstep Adept', 'Shadow', 'unit', 'rare', 3, 3, 3, 'Vanish', '🌫️'),
  ('agi_falconer', 'Roof Runner', 'Shadow', 'unit', 'common', 3, 3, 3, 'Flight', '🏯'),
  ('agi_windblade', 'Wind Blade Kunoichi', 'Shadow', 'unit', 'rare', 4, 4, 3, 'Haste', '🌪️'),
  ('agi_nightblade', 'Nightblade', 'Shadow', 'unit', 'rare', 4, 3, 3, 'Venom', '🌙'),
  ('agi_swiftstrike', 'Swift Strike Ninja', 'Shadow', 'unit', 'rare', 4, 2, 3, 'Flurry', '💠'),
  ('agi_phantom', 'Phantom Stalker', 'Shadow', 'unit', 'rare', 5, 5, 4, 'Stealth', '👤'),
  ('agi_shadowmaster', 'Shadow Master', 'Shadow', 'unit', 'epic', 5, 4, 4, 'Vanish. Battlecry: summon a 2/1 Shadow Wraith.', '🎭'),
  ('agi_reaper', 'Crimson Reaper', 'Shadow', 'unit', 'epic', 6, 5, 5, 'Venom', '🔪'),
  ('agi_tempest', 'Tempest Dancer', 'Shadow', 'unit', 'epic', 6, 4, 4, 'Flurry', '🍥'),
  ('agi_master', 'Grandmaster Shinobi', 'Shadow', 'unit', 'legendary', 7, 6, 6, 'Ambush, Flurry', '🥷'),
  ('agi_oyabun', 'Shadow Oyabun', 'Shadow', 'unit', 'legendary', 8, 6, 6, 'Battlecry: summon two 2/1 Shadow Wraiths and give your units Stealth.', '🐯'),
  ('agi_dash', 'Shunpo', 'Shadow', 'spell', 'common', 1, null, null, 'Give a friendly unit +1/+0 and Haste.', '💨'),
  ('agi_smoke', 'Smoke Bomb', 'Shadow', 'spell', 'common', 1, null, null, 'Give a friendly unit Stealth.', '🌫️'),
  ('agi_ambush', 'Shuriken Strike', 'Shadow', 'spell', 'common', 2, null, null, 'Deal 3 damage to an enemy unit.', '🌟'),
  ('agi_poison', 'Poison Blade', 'Shadow', 'spell', 'rare', 2, null, null, 'Give a friendly unit +1/+0 and Venom.', '🧪'),
  ('agi_backstab', 'Backstab', 'Shadow', 'spell', 'common', 2, null, null, 'Deal 4 damage to an enemy unit.', '🗡️'),
  ('agi_vanishspell', 'Vanishing Act', 'Shadow', 'spell', 'common', 2, null, null, 'Give a friendly unit +1/+1 and Vanish.', '🎇'),
  ('agi_swarm', 'Shadow Clone Jutsu', 'Shadow', 'spell', 'common', 3, null, null, 'Summon two 1/1 Shadow Clones.', '👥'),
  ('agi_volley', 'Shuriken Volley', 'Shadow', 'spell', 'rare', 3, null, null, 'Summon two 1/1 Spinning Shurikens with Haste.', '🎯'),
  ('agi_flurry', 'Blade Flurry', 'Shadow', 'spell', 'rare', 3, null, null, 'Give a friendly unit +1/+0 and Flurry.', '🌀'),
  ('agi_nightraid', 'Night Raid', 'Shadow', 'spell', 'rare', 4, null, null, 'Summon two 2/1 Shadow Wraiths.', '🌃'),
  ('agi_decapitate', 'Decapitate', 'Shadow', 'spell', 'epic', 4, null, null, 'Destroy an enemy unit.', '☠️'),
  ('hrt_medic', 'Healing Monk', 'Shrine', 'unit', 'common', 1, 1, 2, 'Battlecry: restore 2 health to your hero.', '🧎'),
  ('hrt_novice', 'Shrine Novice', 'Shrine', 'unit', 'common', 1, 1, 1, 'Lifesteal', '🕊️'),
  ('hrt_pilgrim', 'Wandering Pilgrim', 'Shrine', 'unit', 'common', 2, 2, 2, 'Battlecry: restore 2 health to your hero.', '🧳'),
  ('hrt_cleric', 'Chi Channeler', 'Shrine', 'unit', 'common', 2, 2, 3, 'Lifesteal', '☯️'),
  ('hrt_acolyte', 'Prayer Acolyte', 'Shrine', 'unit', 'common', 2, 1, 4, 'Guard', '📿'),
  ('hrt_guardian', 'Shrine Guardian', 'Shrine', 'unit', 'common', 3, 2, 5, 'Guard', '⛩️'),
  ('hrt_lifebloom', 'Blossom Sage', 'Shrine', 'unit', 'rare', 3, 2, 2, 'Battlecry: give your units +0/+2.', '🌸'),
  ('hrt_monkdef', 'Iron Palm Monk', 'Shrine', 'unit', 'rare', 3, 3, 3, 'Regenerate', '✊'),
  ('hrt_warden', 'Temple Warden', 'Shrine', 'unit', 'rare', 4, 3, 4, 'Guard, Lifesteal', '🛡️'),
  ('hrt_treant', 'Ancient Bonsai Spirit', 'Shrine', 'unit', 'rare', 4, 3, 6, 'Guard, Regenerate', '🌳'),
  ('hrt_drummer', 'War Monk', 'Shrine', 'unit', 'common', 4, 4, 4, 'Lifesteal', '🥁'),
  ('hrt_kirin', 'Sacred Kirin', 'Shrine', 'unit', 'rare', 5, 4, 4, 'Lifesteal. Battlecry: restore 3 health to your hero.', '🦄'),
  ('hrt_phoenix', 'Phoenix Spirit', 'Shrine', 'unit', 'epic', 5, 4, 4, 'Deathwish: restore 4 health to your hero.', '🐦‍🔥'),
  ('hrt_protector', 'Mountain Protector', 'Shrine', 'unit', 'epic', 5, 2, 8, 'Guard, Regenerate', '🗻'),
  ('hrt_celestguard', 'Celestial Guard', 'Shrine', 'unit', 'rare', 5, 3, 6, 'Guard, Lifesteal', '🏮'),
  ('hrt_spirit_fox', 'Nine Blessings Fox', 'Shrine', 'unit', 'epic', 6, 4, 5, 'Battlecry: summon two 2/2 Fox Spirits.', '🦊'),
  ('hrt_angel', 'Celestial Tengu', 'Shrine', 'unit', 'legendary', 6, 5, 5, 'Lifesteal, Flight', '👺'),
  ('hrt_avatar', 'Avatar of Mercy', 'Shrine', 'unit', 'legendary', 7, 5, 7, 'Guard, Lifesteal. Battlecry: restore 5 health to your hero.', '🌟'),
  ('hrt_blessing', 'Shrine Blessing', 'Shrine', 'spell', 'common', 1, null, null, 'Restore 4 health to your hero.', '🙏'),
  ('hrt_ward', 'Warding Charm', 'Shrine', 'spell', 'common', 1, null, null, 'Give a friendly unit +0/+3.', '🧧'),
  ('hrt_mend', 'Chi Mend', 'Shrine', 'spell', 'common', 2, null, null, 'Give a friendly unit +0/+3 and Regenerate.', '🍃'),
  ('hrt_prayer', 'Group Prayer', 'Shrine', 'spell', 'common', 2, null, null, 'Give your units +0/+2.', '🛐'),
  ('hrt_lifelink', 'Spirit Bond', 'Shrine', 'spell', 'rare', 2, null, null, 'Give a friendly unit +1/+1 and Lifesteal.', '🔗'),
  ('hrt_barrier', 'Stone Barrier', 'Shrine', 'spell', 'rare', 3, null, null, 'Give a friendly unit +0/+4 and Guard.', '🧱'),
  ('hrt_grace', 'Divine Grace', 'Shrine', 'spell', 'rare', 3, null, null, 'Give your units +0/+3.', '🕊️'),
  ('hrt_renewal', 'Spring Renewal', 'Shrine', 'spell', 'rare', 3, null, null, 'Restore 6 health to your hero.', '🌷'),
  ('hrt_sanctuary', 'Sacred Sanctuary', 'Shrine', 'spell', 'rare', 4, null, null, 'Restore 3 health to your hero and give your units +0/+2.', '🏯'),
  ('hrt_bulwark', 'Bulwark Chant', 'Shrine', 'spell', 'epic', 4, null, null, 'Give your units +0/+2 and Regenerate.', '📯'),
  ('hrt_revive', 'Spirit Revival', 'Shrine', 'spell', 'rare', 5, null, null, 'Summon two 2/2 Fox Spirits and restore 3 health to your hero.', '🪷'),
  ('hrt_lastrites', 'Last Rites', 'Shrine', 'spell', 'epic', 6, null, null, 'Restore 8 health to your hero and give your units +0/+2.', '⚱️'),
  ('int_drone', 'Scout Drone', 'Trapmaster', 'unit', 'common', 1, 1, 2, null, '🛸'),
  ('int_mechhound', 'Mech Hound', 'Trapmaster', 'unit', 'common', 2, 3, 1, null, '🐕‍🦺'),
  ('int_turret', 'Spike Trap', 'Trapmaster', 'unit', 'common', 2, 0, 4, 'Guard', '🪤'),
  ('int_engineer', 'Trap Engineer', 'Trapmaster', 'unit', 'rare', 2, 2, 2, 'Battlecry: deal 1 damage to all enemy units.', '🛠️'),
  ('int_tinkerer', 'Trap Tinkerer', 'Trapmaster', 'unit', 'common', 3, 1, 1, 'Battlecry: summon a 2/2 Clay Sentinel.', '🔧'),
  ('int_saboteur', 'Bomb Saboteur', 'Trapmaster', 'unit', 'common', 3, 3, 3, 'Battlecry: deal 2 damage to an enemy unit.', '💣'),
  ('int_spider', 'Trapdoor Spider', 'Trapmaster', 'unit', 'rare', 3, 3, 2, 'Venom', '🕷️'),
  ('int_glider', 'Kite Glider', 'Trapmaster', 'unit', 'common', 3, 2, 3, 'Flight', '🪁'),
  ('int_repairbot', 'Repair Bot', 'Trapmaster', 'unit', 'rare', 3, 2, 3, 'Battlecry: give your units +0/+2.', '🤲'),
  ('int_golemancer', 'Golem Crafter', 'Trapmaster', 'unit', 'rare', 4, 2, 3, 'Battlecry: summon a 2/2 Clay Sentinel.', '🪛'),
  ('int_construct', 'Iron Sentinel', 'Trapmaster', 'unit', 'common', 4, 3, 5, null, '🤖'),
  ('int_warden', 'Iron Warden', 'Trapmaster', 'unit', 'common', 4, 2, 6, 'Guard', '🚧'),
  ('int_summoner', 'Puppet Master', 'Trapmaster', 'unit', 'rare', 5, 3, 3, 'Battlecry: summon two 2/2 Clay Sentinels.', '🎎'),
  ('int_disruptor', 'Mind Disruptor', 'Trapmaster', 'unit', 'rare', 5, 4, 4, 'Battlecry: give an enemy unit -3 Attack.', '🧠'),
  ('int_siege', 'Siege Engine', 'Trapmaster', 'unit', 'epic', 5, 5, 5, 'Battlecry: deal 3 damage to any target.', '🏹'),
  ('int_sentinel2', 'Guardian Construct', 'Trapmaster', 'unit', 'epic', 6, 5, 7, 'Guard', '🗼'),
  ('int_assembler', 'Mech Assembler', 'Trapmaster', 'unit', 'epic', 6, 4, 4, 'Battlecry: summon two 2/2 Clay Sentinels and give your units +1/+0.', '🏭'),
  ('int_colossus', 'War Automaton', 'Trapmaster', 'unit', 'legendary', 7, 7, 7, null, '⚙️'),
  ('int_overlord', 'Clockwork Overlord', 'Trapmaster', 'unit', 'legendary', 8, 7, 8, 'Battlecry: summon two 2/2 Clay Sentinels.', '👑'),
  ('int_disrupt', 'Caltrops', 'Trapmaster', 'spell', 'common', 1, null, null, 'Give an enemy unit -2 Attack.', '🪡'),
  ('int_trapline', 'Tripwire', 'Trapmaster', 'spell', 'common', 1, null, null, 'Deal 2 damage to an enemy unit.', '➰'),
  ('int_overload', 'Explosive Tags', 'Trapmaster', 'spell', 'common', 2, null, null, 'Deal 1 damage to all units.', '🧨'),
  ('int_snare', 'Wire Snare', 'Trapmaster', 'spell', 'rare', 2, null, null, 'Give an enemy unit -3 Attack.', '🕸️'),
  ('int_blast', 'Flash Bomb', 'Trapmaster', 'spell', 'common', 3, null, null, 'Deal 3 damage to any target.', '🎆'),
  ('int_reinforce', 'Reinforce', 'Trapmaster', 'spell', 'rare', 3, null, null, 'Summon two 2/2 Clay Sentinels.', '🔩'),
  ('int_emp', 'EMP Burst', 'Trapmaster', 'spell', 'rare', 3, null, null, 'Give all enemy units -2 Attack.', '📡'),
  ('int_minefield', 'Minefield', 'Trapmaster', 'spell', 'rare', 4, null, null, 'Deal 2 damage to all enemy units.', '💢'),
  ('int_hex', 'Poison Dart', 'Trapmaster', 'spell', 'epic', 4, null, null, 'Destroy an enemy unit.', '☠️'),
  ('int_detonate', 'Detonate', 'Trapmaster', 'spell', 'common', 4, null, null, 'Deal 5 damage to any target.', '🔥'),
  ('int_nuke', 'Orbital Strike', 'Trapmaster', 'spell', 'epic', 6, null, null, 'Deal 5 damage to any target.', '🛰️')
on conflict (code) do update set
  name = excluded.name, clan = excluded.clan, card_type = excluded.card_type,
  rarity = excluded.rarity, cost = excluded.cost, attack = excluded.attack,
  health = excluded.health, rules_text = excluded.rules_text, image_url = excluded.image_url;
